namespace: "universityofderby"
name: "vrealize_log_insight"
version: "0.1.6"
readme: "README.md"
authors:
  - "Richard Lock (University of Derby)"
license:
  - "Apache-2.0"
tags:
  - agent
  - insight
  - log
  - logging
  - vmware
  - vrealize
repository: "https://github.com/universityofderby/ansible-collection-vrealize_log_insight"
