---
- name: Download vRealize Log Insight Agent setup file
  win_get_url:
    url: "{{ vrealize_log_insight_agent_download_url }}"
    dest: "{{ vrealize_log_insight_agent_download_dest }}"

- name: Ensure vRealize Log Insight Agent is installed
  win_package:
    creates_service: LogInsightAgentService
    path: "{{ vrealize_log_insight_agent_download_dest }}"
    state: present

- name: Generate vRealize Log Insight Windows Agent configuration file
  template:
    dest: "{{ vrealize_log_insight_agent_config_path }}"
    src: windows_liagent.ini.j2
  notify:
    - Restart vRealize Log Insight Windows Agent service

- name: Ensure vRealize Log Insight Agent service is set to automatic and started
  win_service:
    description: VMware vRealize Log Insight Agent Service
    display_name: VMware vRealize Log Insight Agent
    name: LogInsightAgentService
    path: "{{ vrealize_log_insight_agent_service_path }}"
    password: ''
    start_mode: auto
    state: started
    username: LocalSystem

- name: Remove vRealize Log Insight Agent setup file
  win_file:
    path: "{{ vrealize_log_insight_agent_download_dest }}"
    state: absent
